const employeeData = [
    {
        "sno": 1,
        "name": "PRAMAТMA SAH",
        "fathersName": "PARMA SAH",
        "age": 48,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 2,
        "name": "DHARMENDRA KUMAR SINGH",
        "fathersName": "VIJAY SINGH",
        "age": 50,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 3,
        "name": "ARJUN SINGH",
        "fathersName": "VIJAY SINGH",
        "age": 26,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 4,
        "name": "GANPAT YADAV",
        "fathersName": "MAFI YADAV",
        "age": 49,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 5,
        "name": "SURENDRA KUMAR SUMAN",
        "fathersName": "BANARSI ROY",
        "age": 57,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 6,
        "name": "PRABIN DAS",
        "fathersName": "RAJNATH DAS",
        "age": 31,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 7,
        "name": "SHREE RAM",
        "fathersName": "DEVNANDAN SINGH",
        "age": 35,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 8,
        "name": "RAHUL PARIHAR",
        "fathersName": "ATMA RAM PARIHAR",
        "age": 30,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 9,
        "name": "DEPAK SINGH DEWDA",
        "fathersName": "PADAM SINGH DEWDA",
        "age": 31,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 10,
        "name": "AWADESH SINGH",
        "fathersName": "ADITTA SINGH",
        "age": 60,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 11,
        "name": "PRADEEP PRAJAPATI",
        "fathersName": "RADHESHYAM PRAJAPATI",
        "age": 27,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 12,
        "name": "VINAY JINDAL",
        "fathersName": "DEEP KUMAR GUPTA",
        "age": 49,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 13,
        "name": "MANISH PRAJAPAT",
        "fathersName": "SHANKER LAL",
        "age": 30,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 14,
        "name": "MOHIT PAL",
        "fathersName": "LALLU PAL",
        "age": 24,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 15,
        "name": "RAHUL SINGH DODIYA",
        "fathersName": "BHAGVAN SINGH DODIYA",
        "age": 19,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 16,
        "name": "GAJENDRA GUJAR",
        "fathersName": "MANGILAL",
        "age": 24,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 17,
        "name": "DILIP",
        "fathersName": "MOHANLAL",
        "age": 35,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 18,
        "name": "ARVIND KUMAR",
        "fathersName": "SURESH RAM",
        "age": 40,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 19,
        "name": "GAUTAM KUMAR SINGH",
        "fathersName": "NAVAL KISHOR SINGH",
        "age": 36,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 20,
        "name": "SANJAY PASWAN",
        "fathersName": "PANCHAM PASWAN",
        "age": 29,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 21,
        "name": "KUSHAL SINGH",
        "fathersName": "KARAN SINGH",
        "age": 29,
        "date": "2026-05-19",
        "gender": "MALE",
    },
    {
        "sno": 22,
        "name": "DASHRATH",
        "fathersName": "BALU SINGH",
        "age": 28,
        "date": "2026-05-19",
        "gender": "MALE",
    }
]

export default employeeData