import React, { useMemo } from "react";
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc.js";
import customParseFormat from "dayjs/plugin/customParseFormat.js";

import isSameOrAfter from "dayjs/plugin/isSameOrAfter";
import isSameOrBefore from "dayjs/plugin/isSameOrBefore";

dayjs.extend(isSameOrAfter);
dayjs.extend(isSameOrBefore);

dayjs.extend(utc);
dayjs.extend(customParseFormat);

const rawData = [
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Rajpal",
    "age": 35,
    "gender": "MALE",
    "mobile": 9752706132,
    "department": "URJA",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- PCM",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Body pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-05",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sandeep Bharod",
    "age": 28,
    "gender": "MALE",
    "mobile": 9972889024,
    "department": "ILA",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Calpol",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Right side shoulder pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-05",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Gourav Sahu",
    "age": 26,
    "gender": "MALE",
    "mobile": 7389343413,
    "department": "OPS",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Ibuprofen",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Right hand middle finger swelling",
    "primaryComplaintCategory": "Swelling",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-06",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sandeep Solanki",
    "age": 32,
    "gender": "MALE",
    "mobile": 7999592412,
    "department": "Security",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Cap- Becomplex",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Mouth Ulcer",
    "primaryComplaintCategory": "Mouth Ulcer",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-06",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Jitendra",
    "age": 42,
    "gender": "MALE",
    "mobile": 9977117856,
    "department": "Production",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Avil",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Allergic reaction",
    "primaryComplaintCategory": "Allergy",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-06",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Ranjeet",
    "age": 22,
    "gender": "MALE",
    "mobile": 6266601952,
    "department": "Core shop",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Avil",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Allergic reaction",
    "primaryComplaintCategory": "Allergy",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-07",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sunil  Katare",
    "age": 30,
    "gender": "MALE",
    "mobile": 6267111266,
    "department": "Core shop",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Cheston cold",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-10",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Rajkumar",
    "age": 30,
    "gender": "MALE",
    "mobile": 7999024973,
    "department": "Driver",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Cheston cold",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-11",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Ranjeet Jakdale",
    "age": 35,
    "gender": "MALE",
    "mobile": 8959955542,
    "department": "URJA",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Cheston cold",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-11",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Pooja",
    "age": 27,
    "gender": "FEMALE",
    "mobile": "",
    "department": "Core shop",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Glucon-D",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Body Weakness",
    "primaryComplaintCategory": "Weakness",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-12",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Manoj Kuilodiya",
    "age": 36,
    "gender": "MALE",
    "mobile": 9380215455,
    "department": "OPS",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab-Disprin",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-16",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Aarti Jhadam",
    "age": 26,
    "gender": "FEMALE",
    "mobile": 7828643816,
    "department": "Core shop",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab-Disprin",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-17",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Ravi Ninama",
    "age": 30,
    "gender": "MALE",
    "mobile": 9575417550,
    "department": "HK",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Cheston cold",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-18",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "G.Tiwari",
    "age": 33,
    "gender": "MALE",
    "mobile": 9131839628,
    "department": "OPS",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Electral powder",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Body Weakness",
    "primaryComplaintCategory": "Weakness",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-18",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Vikas Tiwari",
    "age": 33,
    "gender": "MALE",
    "mobile": 8319684905,
    "department": "Store",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Bainded",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Home injury",
    "primaryComplaintCategory": "Injury",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-19",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Balram Bhabar",
    "age": 31,
    "gender": "MALE",
    "mobile": 9575799237,
    "department": "HK",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab-PCM",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Body pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-19",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Chitramal Devariya",
    "age": 49,
    "gender": "MALE",
    "mobile": 9575244176,
    "department": "Production",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Volini spray, Tab-PCM",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Back pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-19",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Deelip Ahirwar",
    "age": 35,
    "gender": "MALE",
    "mobile": 9294632029,
    "department": "Security",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab-Calpol",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Body pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-21",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Dinesh Solanki",
    "age": 39,
    "gender": "MALE",
    "mobile": 7389848106,
    "department": "Production",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab-PCM",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Fever",
    "primaryComplaintCategory": "Fever",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-21",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Aarti Jhadam",
    "age": 26,
    "gender": "FEMALE",
    "mobile": 7828643816,
    "department": "Core shop",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Ciplox eye drop",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Both Eye pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-22",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sudha Bai",
    "age": 45,
    "gender": "FEMALE",
    "mobile": "",
    "department": "Canteen",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- PCM",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Body pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-22",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Omprakash Jharbade",
    "age": 50,
    "gender": "MALE",
    "mobile": 7389095920,
    "department": "Electrcle",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab-Cheston cold",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-23",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sachin Patel",
    "age": 32,
    "gender": "MALE",
    "mobile": 9754776203,
    "department": "Production",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab-Cheston cold",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-28",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Pawan kumariya",
    "age": 26,
    "gender": "MALE",
    "mobile": 9111233827,
    "department": "ILA",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Sporlac DS",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Loose Motion",
    "primaryComplaintCategory": "Loose Motion",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-29",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Ravi Ninama",
    "age": 30,
    "gender": "MALE",
    "mobile": 9575417550,
    "department": "HK",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab- Buscogust",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Abdominal  Pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-30",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Vijay Gour",
    "age": 51,
    "gender": "MALE",
    "mobile": 9926023353,
    "department": "OPS",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Spray,Tab- calpol",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Right hand Shoulder pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-30",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Mubarik Patel",
    "age": 43,
    "gender": "MALE",
    "mobile": 8894000919,
    "department": "OPS",
    "rest": "FALSE",
    "complaint": "",
    "medicine": "Tab-Ibuprofen",
    "underMedication": "FALSE",
    "fitToWork": "TRUE",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "TREATED_IN_OHC",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "Khushbu Mewada",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "Closed",
    "date": "2026-03-30",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Vijay Gour",
    "age": 51,
    "gender": "MALE",
    "mobile": 9926023353,
    "department": "OPS",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Aciloc",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Acidity",
    "primaryComplaintCategory": "Acidity",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Chitramal Devariya",
    "age": 49,
    "gender": "MALE",
    "mobile": 9575244176,
    "department": "Production",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Aciloc",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Acidity",
    "primaryComplaintCategory": "Acidity",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Ramsingh",
    "age": 42,
    "gender": "MALE",
    "mobile": 8982807884,
    "department": "Security",
    "rest": "",
    "complaint": "",
    "medicine": "Tab- Saridon",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Dolly Nagora",
    "age": 25,
    "gender": "MALE",
    "mobile": 9098442925,
    "department": "Core shop",
    "rest": "",
    "complaint": "",
    "medicine": "Tab- Cheston cold",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sandeep Singh",
    "age": 32,
    "gender": "MALE",
    "mobile": 7999592417,
    "department": "Security",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Disprin",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sandeep Singh",
    "age": 33,
    "gender": "MALE",
    "mobile": 7999592418,
    "department": "Security",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Maftal spas",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Abdominal  Pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Devi Singh",
    "age": 38,
    "gender": "MALE",
    "mobile": 9977418529,
    "department": "HK",
    "rest": "",
    "complaint": "",
    "medicine": "Tab- Calpol",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Body pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Goutam Chouhan",
    "age": 30,
    "gender": "MALE",
    "mobile": 9630154911,
    "department": "Security",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Cheston cold",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Hariom",
    "age": 44,
    "gender": "MALE",
    "mobile": 9617588189,
    "department": "ME",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Sporlec DS",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Loose Motion",
    "primaryComplaintCategory": "Loose Motion",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Dolly Nagora",
    "age": 25,
    "gender": "MALE",
    "mobile": 9098442925,
    "department": "Core shop",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Saridon",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Jitendra Singh",
    "age": 35,
    "gender": "MALE",
    "mobile": 9165966902,
    "department": "F&A",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Cheston cold",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Dara Singh",
    "age": 32,
    "gender": "MALE",
    "mobile": 8965048747,
    "department": "Production",
    "rest": "",
    "complaint": "",
    "medicine": "ENO",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Acidity",
    "primaryComplaintCategory": "Acidity",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sarvan",
    "age": 35,
    "gender": "MALE",
    "mobile": 9074201844,
    "department": "OPS",
    "rest": "",
    "complaint": "",
    "medicine": "ENO",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Acidity",
    "primaryComplaintCategory": "Acidity",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "P.S Rathore",
    "age": 43,
    "gender": "MALE",
    "mobile": 9754700746,
    "department": "Production",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Disprin",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "R.S parmar",
    "age": 42,
    "gender": "MALE",
    "mobile": 8982807884,
    "department": "Security",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Aciloc",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Acidity",
    "primaryComplaintCategory": "Acidity",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Kunjan Patel",
    "age": 44,
    "gender": "MALE",
    "mobile": 9753507972,
    "department": "Security",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-PCM",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Body pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sunil Dabar",
    "age": 32,
    "gender": "MALE",
    "mobile": 9685903562,
    "department": "Production",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Sporlec DS",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Loose Motion",
    "primaryComplaintCategory": "Loose Motion",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Ranjeet",
    "age": 35,
    "gender": "MALE",
    "mobile": 8959955542,
    "department": "HK",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Calpol",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Body pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sandeep Bharod",
    "age": 28,
    "gender": "MALE",
    "mobile": 9977889024,
    "department": "ILA",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Aciloc",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Acidity",
    "primaryComplaintCategory": "Acidity",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Dharmendra Choudhary",
    "age": 39,
    "gender": "MALE",
    "mobile": 9770782702,
    "department": "Production",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Saridon",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Rajesh vastwar",
    "age": 42,
    "gender": "MALE",
    "mobile": 8349505212,
    "department": "Driver",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Calpol",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Body pain",
    "primaryComplaintCategory": "Pain",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Maya Ram",
    "age": 29,
    "gender": "MALE",
    "mobile": 7879475321,
    "department": "Packing",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Cheston cold",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Sonam Sharma",
    "age": 22,
    "gender": "FEMALE",
    "mobile": 9111211988,
    "department": "Core shop",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Disprin",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Headache",
    "primaryComplaintCategory": "Headache",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  },
  {
    "bp": "",
    "corpId": "ee825bad-ed64-46ed-a3a2-67a17f81ac7f",
    "empId": "",
    "name": "Suresh Katare",
    "age": 25,
    "gender": "MALE",
    "mobile": 7610255732,
    "department": "HK",
    "rest": "",
    "complaint": "",
    "medicine": "Tab-Cheston cold",
    "underMedication": "",
    "fitToWork": "",
    "nextAppointmentDate": "",
    "files": "",
    "ohcType": "",
    "injuryRemarks": "",
    "injuryType": "",
    "injuryLocation": "",
    "uploadedUrls": "",
    "treatmentDoneAt": "",
    "injurySeverity": "",
    "primaryComplaint": "Cold & cough",
    "primaryComplaintCategory": "Cold",
    "secondaryComplaint": "",
    "otherComplaint": "",
    "remarks": "",
    "injuryBodyPart": "",
    "injuryBodyLocation": "",
    "recordKeeper": "",
    "incidentDepartment": "",
    "incidentMachine": "",
    "incidentShift": "",
    "referredHospitalName": "",
    "unsafeTag": "",
    "injuryReportType": "",
    "opdCaseStatus": "",
    "date": "",
    "caseRecordTimeStamp": ""
  }
]
  ?.map((item) => ({
    ...item,
    // age: item?.age?.toString(),
    // // mobile: item?.mobile?.toString(),
    ohcType: "OPD",
    empId: item?.empId?.toString(),
    corpId: '9b7e33eb-d085-4df5-bdc1-146d930c2387',
    fitToWork: item?.fitToWork === "TRUE" ? true : item?.fitToWork === "FALSE" ? false : null,
    underMedication: item?.underMedication === "TRUE" ? true : item?.underMedication === "FALSE" ? false : null,
    rest: item?.rest === "TRUE" ? true : item?.rest === "FALSE" ? false : null,
    // gender: item.gender === "Male" ? "MALE" : item.gender === "Female" ? "FEMALE" : "",
  }))
// ?.map((item) => {
//   const meds = [];

//   const med1 = item["Medicine Provided for Complaint 1"];
//   const qty1 = item["Quantity 1"];

//   const med2 = item["Medicine Provided for Complaint 2"];
//   const qty2 = item["Quantity 2"];

//   const med3 = item["Medicine Provided for Complaint 3"];
//   const qty3 = item["Quantity 3"];

//   if (med1 && med1 !== "NA" && qty1 && qty1 !== "NA") {
//     meds.push(`${med1} - QTY - ${qty1}`);
//   }
//   if (med2 && med2 !== "NA" && qty2 && qty2 !== "NA") {
//     meds.push(`${med2} - QTY - ${qty2}`);
//   }
//   if (med3 && med3 !== "NA" && qty3 && qty3 !== "NA") {
//     meds.push(`${med3} - QTY - ${qty3}`);
//   }

//   // Convert date -> YYYY-MM-DD
//   // const formattedDate = dayjs(item.date, ["D-MMM-YY", "DD-MMM-YY"]).format(
//   //   "YYYY-MM-DD"
//   // );

//   // Remove original medicine fields
//   const {
//     "Medicine Provided For Complaint 1": _m1,
//     "Quantity 1": _q1,
//     "Medicine Provided for Complaint 2": _m2,
//     "Quantity 2": _q2,
//     "Medicine Provided for Complaint 3": _m3,
//     "Quantity 3": _q3,
//     "Name of UNO Care Staff": _uno,
//     "Name of the Dr.(FMO)": _doctor,
//     MEDICINE: _m,
//     "Health Complaint 1": _hc1,
//     ...rest
//   } = item;

//   return {
//     ...rest,
//     date: item?.date,
//     medicine: meds.length > 0 ? meds.join(", ") : "NA",
//   };
// });

const cleanAndNormalizeData = (data) => {
  if (!Array.isArray(data)) return [];

  // ✅ List of all supported formats — short, long, and mixed
  const dateFormats = [
    "D-MMM-YY",
    "DD-MMM-YY",
    "D-MMM-YYYY",
    "DD-MMM-YYYY",
    "D/M/YYYY",
    "DD/M/YYYY",
    "D/MM/YYYY",
    "DD/MM/YYYY",
    "D-M-YYYY",
    "DD-MM-YYYY",
    "DD-MM-YY",
    "D-M-YY",
    "M/D/YYYY",
    "MM/DD/YYYY",
    "M/D/YY",
    "MM/DD/YY",
    "YYYY-MM-DD",
    "YYYY/MM/DD",
    "YYYY-M-D",
    "D MMM YYYY",
    "D MMM YY",
    "DD/MM/YY",
    "D/M/YY",
  ];

  return data.map((item) => {
    const normalized = { ...item };

    // --- 1️⃣ Normalize date to YYYY-MM-DD ---
    let parsedDate = null;
    if (normalized.date) {
      // Try all known formats
      for (const fmt of dateFormats) {
        const tryParse = dayjs(normalized.date, fmt, true);
        if (tryParse.isValid()) {
          parsedDate = tryParse;
          break;
        }
      }

      // If none worked, try free-form parse (last resort)
      if (!parsedDate) {
        const autoParsed = dayjs(normalized.date);
        if (autoParsed.isValid()) parsedDate = autoParsed;
      }

      normalized.date = parsedDate ? parsedDate.format("YYYY-MM-DD") : "";
    } else {
      normalized.date = "";
    }

    // --- 2️⃣ Generate caseRecordTimeStamp ---
    const dateStr = normalized.date?.trim?.();
    const timeStr = normalized.caseRecordTimeStamp?.trim?.();

    if (dateStr && timeStr && !timeStr.includes("T")) {
      let parsed = dayjs(`${dateStr} ${timeStr}`, [
        "YYYY-MM-DD HH:mm",
        "YYYY-MM-DD hh:mm A",
        "YYYY-MM-DD H:mm",
        "YYYY-MM-DD h:mm A",
      ]);

      normalized.caseRecordTimeStamp = parsed.isValid()
        ? parsed.utc().format("YYYY-MM-DDTHH:mm:ss.SSS[Z]")
        : "";
    } else if (timeStr && timeStr.includes("T")) {
      const parsed = dayjs(timeStr);
      normalized.caseRecordTimeStamp = parsed.isValid()
        ? parsed.utc().format("YYYY-MM-DDTHH:mm:ss.SSS[Z]")
        : "";
    } else {
      normalized.caseRecordTimeStamp = "";
    }

    // --- 3️⃣ Remove null/empty fields ---
    const cleaned = Object.fromEntries(
      Object.entries(normalized).filter(([_, value]) => {
        if (value === null || value === undefined) return false;
        if (typeof value === "string" && value.trim() === "") return false;
        if (Array.isArray(value) && value.length === 0) return false;
        return true;
      })
    );

    return cleaned;
  });
};

const UploadDataOPD = ({ }) => {
  // const cleanedData = useMemo(() => cleanObject(rawData), [rawData]);
  const formatted = useMemo(() => cleanAndNormalizeData(rawData), [rawData]);

  console.log({ formatted });

  return <div></div>;
};

export default UploadDataOPD;
