import React, { useMemo } from "react";
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc.js";
import customParseFormat from "dayjs/plugin/customParseFormat.js";

dayjs.extend(utc);
dayjs.extend(customParseFormat);

const rawData = [
  {
    empId: "9743",
    name: "Navnath Shinde",
    department: "Changing",
    recordedDate: "2025-11-01",
    recordedTime: "00:13",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Gas",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Gasex",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "9118",
    name: "Dipak Bhosale",
    department: "Production",
    recordedDate: "2025-11-01",
    recordedTime: "10:50",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "2052",
    name: "Vidya Mandhare",
    department: "Admin",
    recordedDate: "2025-11-01",
    recordedTime: "11:55",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Loose Motion",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Lomotil",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "8649",
    name: "Vijay Deshmane",
    department: "Store",
    recordedDate: "2025-11-01",
    recordedTime: "14:45",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Back Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "5684",
    name: "Avdhut Jadhav",
    department: "PFD",
    recordedDate: "2025-11-01",
    recordedTime: "19:20",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Body Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tan Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "4018",
    name: "L. S. Konde",
    department: "Production",
    recordedDate: "2025-11-01",
    recordedTime: "22:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Loose Motion",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Lomotil",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "3821",
    name: "C. S. Sonwane",
    department: "QC",
    recordedDate: "2025-11-01",
    recordedTime: "12:50",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Body Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "4680",
    name: "Vishwajeet Bhondale",
    department: "Production",
    recordedDate: "2025-11-01",
    recordedTime: "21:50",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Gas",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Gasex",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "4706",
    name: "Mahesh Sonwane",
    department: "Eng ",
    recordedDate: "2025-11-01",
    recordedTime: "22:05",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Muscle Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Sumo Spray",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "8089",
    name: "Ram Patel",
    department: "Gelatin",
    recordedDate: "2025-11-02",
    recordedTime: "04:05",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Muscle Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Sumo Spray",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "3266",
    name: "Dhanaji Gaikwad",
    department: "Driver",
    recordedDate: "2025-11-02",
    recordedTime: "05:10:00",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Headache",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Dolokind AA",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "4935",
    name: "Rohit Kumar",
    department: "BSR",
    recordedDate: "2025-11-02",
    recordedTime: "06:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Acidity",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cyra",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "1144",
    name: "Harshad Tandure",
    department: "QC",
    recordedDate: "2025-11-02",
    recordedTime: "08:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Body Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tan Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "3268",
    name: "Kiran Kakade",
    department: "PFD",
    recordedDate: "2025-11-02",
    recordedTime: "00:13",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Sore Throat",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cofsils",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "6504",
    name: "Jitendra Singh",
    department: "AC",
    recordedDate: "2025-11-02",
    recordedTime: "11:55",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Back Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "7060",
    name: "Ram Jagtap",
    department: "PFD",
    recordedDate: "2025-11-02",
    recordedTime: "04:05",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Abdomen Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tan Spasmonil",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "5684",
    name: "Avdhut Jadhav",
    department: "PFD",
    recordedDate: "2025-11-02",
    recordedTime: "05:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "7537",
    name: "Dinanath Morade",
    department: "PFD",
    recordedDate: "2025-11-02",
    recordedTime: "08:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "1412",
    name: "Rohidas Shinde",
    department: "Production",
    recordedDate: "2025-11-02",
    recordedTime: "09:50",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Sore Throat",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cofsils",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "1111",
    name: "Nirmala Sadgir",
    department: "Security",
    recordedDate: "2025-11-02",
    recordedTime: "10:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Acidity",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cyra",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "2541",
    name: "Nilesh Vedpathak",
    department: "QC",
    recordedDate: "2025-11-02",
    recordedTime: "11:55",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "9809",
    name: "Pandurang Wagh",
    department: "Washing",
    recordedDate: "2025-11-02",
    recordedTime: "00:40",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Itching ",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Levocet",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "5234",
    name: "Navnath Kakde",
    department: "IT",
    recordedDate: "2025-11-02",
    recordedTime: "04:05",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Headache",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab PCM",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "9030",
    name: "Dilip Kumar",
    department: "Gelatin",
    recordedDate: "2025-11-02",
    recordedTime: "05:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Acidity",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cyra",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "1205",
    name: "Kamal Ashraf",
    department: "Gelatin",
    recordedDate: "2025-11-02",
    recordedTime: "08:45",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Toothache",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Ketorol",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "4018",
    name: "L. S. Konde",
    department: "Production",
    recordedDate: "2025-11-02",
    recordedTime: "16:20",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Loose Motion",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Lomotil",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "6504",
    name: "Jitendra Singh",
    department: "Production",
    recordedDate: "2025-11-02",
    recordedTime: "17:45",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Headache",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Pcm",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "7537",
    name: "Dinanath Morade",
    department: "PFD",
    recordedDate: "2025-11-02",
    recordedTime: "21:55",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Headache",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Pcm",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "6940",
    name: "Kiran Sankapal",
    department: "Production",
    recordedDate: "2025-11-03",
    recordedTime: "05:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "4487",
    name: "Rahul Bhate",
    department: "Production",
    recordedDate: "2025-11-03",
    recordedTime: "08:45",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Nausea",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Emeset",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "9110",
    name: "Akash Wankhede",
    department: "Store",
    recordedDate: "2025-11-03",
    recordedTime: "12:15",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Body Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "2222",
    name: "Adhik Dhumal",
    department: "QC",
    recordedDate: "2025-11-03",
    recordedTime: "14:45",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "1198",
    name: "Raj Kumar",
    department: "Gelatin",
    recordedDate: "2025-11-03",
    recordedTime: "17:20",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Stomach Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Spasmonil",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "9810",
    name: "Atul Wakud",
    department: "gelatin",
    recordedDate: "2025-11-04",
    recordedTime: "20:40",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "9343",
    name: "Alpesh Kumar",
    department: "BSR",
    recordedDate: "2025-11-04",
    recordedTime: "21:50",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "1062",
    name: "Vaibhav Sangekar",
    department: "Canteen",
    recordedDate: "2025-11-04",
    recordedTime: "22:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Acidity",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cyra",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "8969",
    name: "L. S. Konde",
    department: "Production",
    recordedDate: "2025-11-04",
    recordedTime: "22:20",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "gas",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Gasex",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "6136",
    name: "Sanjay Mangare",
    department: "Production",
    recordedDate: "2025-11-04",
    recordedTime: "23:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Back Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Dolokind AA",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "7537",
    name: "Dinanath Morade",
    department: "pfd",
    recordedDate: "2025-11-05",
    recordedTime: "23:20",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "7060",
    name: "Ram Jagtap",
    department: "pfd",
    recordedDate: "2025-11-05",
    recordedTime: "23:30",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Body Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "1331",
    name: "Dattatray Khopade",
    department: "QC",
    recordedDate: "2025-11-05",
    recordedTime: "05:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Acidity",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cyra",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "2668",
    name: "Jayvant Dhaigude",
    department: "QC",
    recordedDate: "2025-11-05",
    recordedTime: "08:20",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Body Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "2700",
    name: "Pravin Shirole",
    department: "QC",
    recordedDate: "2025-11-06",
    recordedTime: "10:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Body Pain",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Ibugesic Plus",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "8132",
    name: "Bharat Gaikwad",
    department: "Garden",
    recordedDate: "2025-11-06",
    recordedTime: "11:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Acidity",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cyra",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "2003",
    name: "Ganesh Jadhav",
    department: "QC",
    recordedDate: "2025-11-06",
    recordedTime: "22:10",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Acidity",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cyra",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "7823",
    name: "Robin Mishra",
    department: "pfd",
    recordedDate: "2025-11-06",
    recordedTime: "04:05",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "cold",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cheston Cold",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "9735",
    name: "Kartik Chinchole",
    department: "Production",
    recordedDate: "2025-11-06",
    recordedTime: "11:55",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Headache",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Pcm",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "2694",
    name: "Ravindra Shinde",
    department: "store",
    recordedDate: "2025-11-07",
    recordedTime: "00:40",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Acidity",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Cyra",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
  {
    empId: "9354",
    name: "Rohit Kumar",
    department: "BSR",
    recordedDate: "2025-11-07",
    recordedTime: "18:05",
    bp: "",
    sugar: "",
    height: "",
    weight: "",
    complaint: "Headache",
    primaryComplaint: "",
    secondaryComplaint: "",
    remarks: "",
    medicine: "Tab Pcm",
    rest: "",
    fitToWork: true,
    underMedication: "",
    nextAppointmentDate: "",
    recordKeeper: "Ramnarayan Awad",
    treatmentDoneAt: "OHC",
    ohcType: "OPD",
    corpId: "a06a682a-dd22-4f97-9516-ccaf9744dd0c",
  },
];

const cleanAndNormalizeData = (data) => {
  if (!Array.isArray(data)) return [];

  // ✅ List of all supported formats — short, long, and mixed
  const dateFormats = [
    "D-MMM-YY",
    "DD-MMM-YY",
    "D-MMM-YYYY",
    "DD-MMM-YYYY",
    "D/M/YYYY",
    "DD/M/YYYY",
    "D/MM/YYYY",
    "DD/MM/YYYY",
    "D-M-YYYY",
    "DD-MM-YYYY",
    "DD-MM-YY",
    "D-M-YY",
    "M/D/YYYY",
    "MM/DD/YYYY",
    "M/D/YY",
    "MM/DD/YY",
    "YYYY-MM-DD",
    "YYYY/MM/DD",
    "YYYY-M-D",
    "D MMM YYYY",
    "D MMM YY",
  ];

  return data.map((item) => {
    const normalized = { ...item };

    // --- 1️⃣ Normalize date to YYYY-MM-DD ---
    let parsedDate = null;
    if (normalized.date) {
      // Try all known formats
      for (const fmt of dateFormats) {
        const tryParse = dayjs(normalized.date, fmt, true);
        if (tryParse.isValid()) {
          parsedDate = tryParse;
          break;
        }
      }

      // If none worked, try free-form parse (last resort)
      if (!parsedDate) {
        const autoParsed = dayjs(normalized.date);
        if (autoParsed.isValid()) parsedDate = autoParsed;
      }

      normalized.date = parsedDate ? parsedDate.format("YYYY-MM-DD") : "";
    } else {
      normalized.date = "";
    }

    // --- 2️⃣ Generate caseRecordTimeStamp ---
    const dateStr = normalized.date?.trim?.();
    const timeStr = normalized.caseRecordTimeStamp?.trim?.();

    if (dateStr && timeStr && !timeStr.includes("T")) {
      let parsed = dayjs(`${dateStr} ${timeStr}`, [
        "YYYY-MM-DD HH:mm",
        "YYYY-MM-DD hh:mm A",
        "YYYY-MM-DD H:mm",
        "YYYY-MM-DD h:mm A",
      ]);

      normalized.caseRecordTimeStamp = parsed.isValid()
        ? parsed.utc().format("YYYY-MM-DDTHH:mm:ss.SSS[Z]")
        : "";
    } else if (timeStr && timeStr.includes("T")) {
      const parsed = dayjs(timeStr);
      normalized.caseRecordTimeStamp = parsed.isValid()
        ? parsed.utc().format("YYYY-MM-DDTHH:mm:ss.SSS[Z]")
        : "";
    } else {
      normalized.caseRecordTimeStamp = "";
    }

    // --- 3️⃣ Remove null/empty fields ---
    const cleaned = Object.fromEntries(
      Object.entries(normalized).filter(([_, value]) => {
        if (value === null || value === undefined) return false;
        if (typeof value === "string" && value.trim() === "") return false;
        if (Array.isArray(value) && value.length === 0) return false;
        return true;
      })
    );

    return cleaned;
  });
};

const UploadDataOPD = ({}) => {
  // const cleanedData = useMemo(() => cleanObject(rawData), [rawData]);
  const formatted = useMemo(() => cleanAndNormalizeData(rawData), [rawData]);

  console.log({ formatted });

  return <div></div>;
};

export default UploadDataOPD;
