import React, { useMemo } from "react";
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc.js";
import customParseFormat from "dayjs/plugin/customParseFormat.js";

dayjs.extend(utc);
dayjs.extend(customParseFormat);

const rawData = [
  {
    date: "02/11/25",
    name: "VISHAL GUPTA",
    empId: "",
    department: "CANTEEN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "CAP PAD D",
    bp: "",
    sugar: "",
    weight: "",
    age: 36,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "04/11/25",
    name: "MAHADEV BODAK",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "CAP PAD D",
    bp: "",
    sugar: "",
    weight: "",
    age: 36,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "04/11/25",
    name: "AKHILESH YADAV",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "CAP PAD D",
    bp: "",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "05/11/25",
    name: "VINAYAK ATKIRE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "T.PAN 40",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "08/11/25",
    name: "VINAYAK ATKIRE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "T.PAN 40",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "TUSHAR SHING",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "T.PAN 40",
    bp: "",
    sugar: "",
    weight: "",
    age: 20,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "12/11/25",
    name: "ANKUR IAISWAR",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "CAP PAD D",
    bp: "",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "PRAVIN KUBHAR",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "T.PAN 40",
    bp: "",
    sugar: "",
    weight: "",
    age: 45,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "DYANAD KORLEKAR",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "T.PAN 40",
    bp: "",
    sugar: "",
    weight: "",
    age: 44,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "VINOD KUMAR",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "CAP PAD D",
    bp: "",
    sugar: "",
    weight: "",
    age: 41,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "16/11/25",
    name: "VIVIK",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "CAP- PAD D",
    bp: "",
    sugar: "",
    weight: "",
    age: 49,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "16/11/25",
    name: "ARUN  DAS",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "CAP- PAD D",
    bp: "",
    sugar: "",
    weight: "",
    age: 60,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "19/11/25",
    name: "DADASAHEB",
    empId: "",
    department: "GELETING",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "CAP.PAN D",
    bp: "",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "29/11/25",
    name: "ARUN DAS",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Gastric",
    medicine: "T.PAN 40",
    bp: "",
    sugar: "",
    weight: "",
    age: 60,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "24/11/25",
    name: "SUNIL NARRE",
    empId: "",
    department: "PRODAUTIAN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.ACELOMR",
    bp: "",
    sugar: "",
    weight: "",
    age: 52,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "04/11/25",
    name: "BABLU RAUT",
    empId: "",
    department: "PRODAUTIAN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICOD",
    bp: "",
    sugar: "",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "04/11/25",
    name: "GANESH CHAVHAN",
    empId: "",
    department: "ETP",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICOD",
    bp: "",
    sugar: "",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "04/11/25",
    name: "ARUN RAUT",
    empId: "",
    department: "WASSING",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.ACELOMR",
    bp: "",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "05/11/25",
    name: "YOGESH YADAV",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICOD",
    bp: "",
    sugar: "",
    weight: "",
    age: 21,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "PARSHARAM   SUTAR",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.ACELOMR",
    bp: "",
    sugar: "",
    weight: "",
    age: 26,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "13/11/25",
    name: "DADASAHEB NIKAJE",
    empId: "",
    department: "GELETING",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "17/11/25",
    name: "SANTOSH  KUMAR",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 29,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "17/11/25",
    name: "SADASIV",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 36,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "20/11/25",
    name: "DILLIP RAUT",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 37,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "20/11/25",
    name: "AJEET RAUT",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.BRUFEN",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "22/11/25",
    name: "CHANDRAKANT BURE",
    empId: "",
    department: "ESD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 43,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "26/11/25",
    name: "PRANISH PATIL",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 35,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "28/11/25",
    name: "LOVESH NALAVDE",
    empId: "",
    department: "PRODAUTIAN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.DICOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 29,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "28/11/25",
    name: "VINAYAK ATKIRE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.ACELOMR",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "28/11/25",
    name: "JAYRAM",
    empId: "",
    department: "Mucileage Preparation",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.ACELOMR",
    bp: "",
    sugar: "",
    weight: "",
    age: 49,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "30/11/25",
    name: "ABIJEET CHAVHAN",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Full Body",
    primaryComplaint: "Pain",
    medicine: "T.ACELOMR",
    bp: "",
    sugar: "",
    weight: "",
    age: 29,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "01/11/25",
    name: "ARUN  DAS",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "NA",
    bp: "136/85",
    sugar: "",
    weight: "",
    age: 56,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "01/11/25",
    name: "GIGAR TALAR",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "NA",
    bp: "148/90MMGH",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "01/11/25",
    name: "Mahenra KAMBLE",
    empId: "",
    department: "MUTICAR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "NA",
    bp: "142-80MMGH",
    sugar: "",
    weight: "",
    age: 52,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "02/11/25",
    name: "KALPES SATHAM",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "NA",
    bp: "118/73MMGH",
    sugar: "",
    weight: "",
    age: 39,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "04/11/25",
    name: "MAHENDRA KABLE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "NA",
    bp: "156/85MMGH",
    sugar: "",
    weight: "",
    age: 55,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "05/11/25",
    name: "MAHENDRA KABLE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "NA",
    bp: "120/76MMGH",
    sugar: "",
    weight: "",
    age: 55,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "10/11/25",
    name: "AZIM SAYYED",
    empId: "",
    department: "QC LAB",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "NA",
    bp: "149/99MMGH",
    sugar: "",
    weight: "",
    age: 52,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "10/11/25",
    name: "VIRAJ VARDHAK",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "NA",
    bp: "171/107MMGH",
    sugar: "",
    weight: "",
    age: 36,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "12/11/25",
    name: "SHARIF SHAIHK",
    empId: "",
    department: "STORE",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "120/80MMGH",
    sugar: "",
    weight: "",
    age: 45,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "12/11/25",
    name: "KALPES SATHAM",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "133/72MMGH",
    sugar: "",
    weight: "",
    age: 39,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "12/11/25",
    name: "VIRAJ VARDHAK",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "155/100MMGH",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "17/11/25",
    name: "SANDHYA JADAV",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "98/64MMGH",
    sugar: "",
    weight: "",
    age: 26,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "17/11/25",
    name: "JUIEC DAMAUHN",
    empId: "",
    department: "145 PLOT",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "118/70MMGH",
    sugar: "",
    weight: "",
    age: 23,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "26/11/25",
    name: "LALIT PATIL",
    empId: "",
    department: "Mucileage Preparation",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "140/107MMGH",
    sugar: "",
    weight: "",
    age: 47,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "27/11/25",
    name: "LALIT PATIL",
    empId: "",
    department: "Mucileage Preparation",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "150/100MMGH",
    sugar: "",
    weight: "",
    age: 43,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "28/11/25",
    name: "ARUN",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "122/85MMGH",
    sugar: "",
    weight: "",
    age: 43,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "28/11/25",
    name: "MANVEER",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "106/70MMGH",
    sugar: "",
    weight: "",
    age: 48,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "13/11/25",
    name: "VIRAJ VARDHAK",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "175/108MMGH",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "22/11/25",
    name: "VIRAJ VARDHAK",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "152/98MMGH",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "24/11/25",
    name: "RAJESH  MANTRI",
    empId: "",
    department: "PRODAUTIAN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Bp monitoring",
    medicine: "",
    bp: "131/91MMGH",
    sugar: "",
    weight: "",
    age: 52,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "08/11/25",
    name: "RAJESH BHOSALE",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Chest",
    primaryComplaint: "Pain",
    medicine: "T.PAN 40,T.ASPRINT.CLOPILETT.CROCIN",
    bp: "160/102MMGH",
    sugar: "145MGDL",
    weight: "",
    age: 49,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "02/11/25",
    name: "JOKSAN Dabre",
    empId: "",
    department: "BSR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 42,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "06/11/25",
    name: "DYANAD KORLEKAR",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 45,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "06/11/25",
    name: "RAMESH  SALUNKE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "07/11/25",
    name: "DR SURENDRD GUPTA",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVOCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 29,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "07/11/25",
    name: "DYANAD KORLEKAR",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVOCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 45,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "07/11/25",
    name: "BHARITI MACHI",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVOCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "FEMALE",
    remarks: "",
  },
  {
    date: "08/11/25",
    name: "OMPRAKASH GUPTA",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 50,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "BHARITI MACHI",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVOCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 39,
    next_appointment_date: "",
    gender: "FEMALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "SWAPNIL DHAVI",
    empId: "",
    department: "DRIVIR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVOCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 42,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "12/11/25",
    name: "AKHILESH YADAV",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVOCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "12/11/25",
    name: "RANJIT NAYAK",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.COFSILS",
    bp: "",
    sugar: "",
    weight: "",
    age: 48,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "13/11/25",
    name: "PRATIK YADAV",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 20,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "NITIN WHAGHMARE",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "BHARITI MACHI",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 39,
    next_appointment_date: "",
    gender: "FEMALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "RAKESH NAVALE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "15/11/25",
    name: "JOKSAN",
    empId: "",
    department: "BSR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 42,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "15/11/25",
    name: "SAYAMAN DALI",
    empId: "",
    department: "ESD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 21,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "17/11/25",
    name: "SANTOSH GANGE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVOCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 48,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "17/11/25",
    name: "YOGESH YADAV",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 28,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "18/11/25",
    name: "AJINKE PAWAR",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 23,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "19/11/25",
    name: "KIRAN KABLE",
    empId: "",
    department: "ETP",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "19/11/25",
    name: "LOVESH NALAVDE",
    empId: "",
    department: "PRODAUTIAN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LEVCITRAZINE",
    bp: "",
    sugar: "",
    weight: "",
    age: 28,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "19/11/25",
    name: "AKHILESH YADAV",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "20/11/25",
    name: "SHEKHAR SOLAKI",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 22,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "21/11/25",
    name: "SONU GUTA",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 19,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "23/11/25",
    name: "VISHAL GUPTA",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 39,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "24/11/25",
    name: "RAJAN KAN",
    empId: "",
    department: "VENDAR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 62,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "25/11/25",
    name: "PAPPU KHAN",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LOVCITARAZIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "26/11/25",
    name: "SURENDAR YADAV",
    empId: "",
    department: "VENDAR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 49,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "26/11/25",
    name: "SUNDAR",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LOVCITARAZIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 48,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "26/11/25",
    name: "RAKESH NAVALE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.LOVCITARAZIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 39,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "27/11/25",
    name: "MILIND",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: 35,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "28/11/25",
    name: "YASHEAN SHARIF",
    empId: "",
    department: "STORE",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Cold",
    medicine: "T.CHESTONCOLD",
    bp: "",
    sugar: "",
    weight: "",
    age: "",
    next_appointment_date: "",
    gender: "",
    remarks: "",
  },
  {
    date: "09/11/25",
    name: "KEVAL PATEL",
    empId: "",
    department: "OFFLINE",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Fever",
    medicine: "T.DOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 25,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "10/11/25",
    name: "SANIKA  PRULEKAR",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Fever",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: "",
    next_appointment_date: "",
    gender: "",
    remarks: "",
  },
  {
    date: "13/11/25",
    name: "SANDEEP SHETE",
    empId: "",
    department: "QC LAB",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Fever",
    medicine: "T.DOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 50,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "SANIKA  PRULEKAR",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Fever",
    medicine: "T.DOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 23,
    next_appointment_date: "",
    gender: "FEMALE",
    remarks: "",
  },
  {
    date: "26/11/25",
    name: "RASHEE VAYS",
    empId: "",
    department: "HR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Fever",
    medicine: "T.DOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 37,
    next_appointment_date: "",
    gender: "FEMALE",
    remarks: "",
  },
  {
    date: "20/11/25",
    name: "RAJNEET NAYEK",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "Both",
    bodyPartPrimary: "Hand",
    primaryComplaint: "Pain",
    medicine: "T.BRUFEN",
    bp: "",
    sugar: "",
    weight: "",
    age: 48,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "27/11/25",
    name: "BALASHAHEB SHINDE",
    empId: "",
    department: "PRODAUTIAN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.DICOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 42,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "28/11/25",
    name: "MAHENDRA KABLE",
    empId: "",
    department: "STORE",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.DICOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 52,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "28/11/25",
    name: "JAYSINGH",
    empId: "",
    department: "BABA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 39,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "30/11/25",
    name: "DILLIP RAUT",
    empId: "",
    department: "GELETING",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 34,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "10/11/25",
    name: "PROMOD  HIRE",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 36,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "SHILESH YADAV",
    empId: "",
    department: "PRODAUTIAN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.DICLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 25,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "GAURO SINGH",
    empId: "",
    department: "Mucileage Preparation",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 29,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "HEMAT RAUT",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 29,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "CHANDRAKANT BURE",
    empId: "",
    department: "ESD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.DOLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 42,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "12/11/25",
    name: "SAHANS RAUT",
    empId: "",
    department: "PRODAUTIAN",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 35,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "12/11/25",
    name: "MAHENDRA KABLE",
    empId: "",
    department: "STORE",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.DICLO",
    bp: "",
    sugar: "",
    weight: "",
    age: 52,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "18/11/25",
    name: "SHEKHAR SOLAKI",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 22,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "20/11/25",
    name: "PALANYA SWAMI",
    empId: "",
    department: "GELETING",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.BRUFEN",
    bp: "",
    sugar: "",
    weight: "",
    age: 47,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "24/11/25",
    name: "SANJAY GANGE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.CROCIN",
    bp: "",
    sugar: "",
    weight: "",
    age: 37,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "24/11/25",
    name: "RABINDRA BARKHE",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Dizziness",
    medicine: "T.BRUFEN",
    bp: "",
    sugar: "",
    weight: "",
    age: 35,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "24/11/25",
    name: "BALCHAND NANVDE",
    empId: "",
    department: "QC LAB",
    bodyPartPrimaryLocation: "Both",
    bodyPartPrimary: "Leg",
    primaryComplaint: "Pain",
    medicine: "T.BRUFEN",
    bp: "",
    sugar: "",
    weight: "",
    age: 29,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "17/11/25",
    name: "ARUN  CHAVHAN",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Loose Motion",
    medicine: "CAP.ROKO",
    bp: "",
    sugar: "",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "22/11/25",
    name: "SADAM HUSAN",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Loose Motion",
    medicine: "CAP.ROKO",
    bp: "",
    sugar: "",
    weight: "",
    age: 28,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "01/11/25",
    name: "JEET SINGH",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "Left",
    bodyPartPrimary: "Hand",
    primaryComplaint: "Injury",
    medicine: "DRESSING",
    bp: "",
    sugar: "",
    weight: "",
    age: 26,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "19/11/25",
    name: "AJAY JAIWAIL",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "Left",
    bodyPartPrimary: "Hand",
    primaryComplaint: "Injury",
    medicine: "CLEANING",
    bp: "",
    sugar: "",
    weight: "",
    age: 38,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "25/11/25",
    name: "FURKAN SHAIKH",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "Left",
    bodyPartPrimary: "Hand",
    primaryComplaint: "Injury",
    medicine: "CLEANING",
    bp: "",
    sugar: "",
    weight: "",
    age: 21,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "27/11/25",
    name: "HEMANT SINHG",
    empId: "",
    department: "QC LAB",
    bodyPartPrimaryLocation: "Left",
    bodyPartPrimary: "Hand",
    primaryComplaint: "Injury",
    medicine: "DRESSING",
    bp: "",
    sugar: "",
    weight: "",
    age: 29,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "SHREYES SHRIKHE",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Neck",
    primaryComplaint: "Pain",
    medicine: "T.BRUFEN",
    bp: "",
    sugar: "",
    weight: "",
    age: 48,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "04/11/25",
    name: "BALCHAND NANVDE",
    empId: "",
    department: "GELETING",
    bodyPartPrimaryLocation: "Right",
    bodyPartPrimary: "Hand",
    primaryComplaint: "Injury",
    medicine: "T.DICOD",
    bp: "",
    sugar: "",
    weight: "",
    age: 39,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "ROSHAN BHAGDE",
    empId: "",
    department: "BABA",
    bodyPartPrimaryLocation: "Right",
    bodyPartPrimary: "Hand",
    primaryComplaint: "Injury",
    medicine: "BANDAID",
    bp: "",
    sugar: "",
    weight: "",
    age: 30,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "01/11/25",
    name: "SIMAND DABHI",
    empId: "",
    department: "AC",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Injury",
    medicine: "DRESSING",
    bp: "",
    sugar: "",
    weight: "",
    age: 21,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "02/11/25",
    name: "OMPRAKASH GUPTA",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Injury",
    medicine: "BANDAID",
    bp: "",
    sugar: "",
    weight: "",
    age: 45,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "07/11/25",
    name: "M JOSAB",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Injury",
    medicine: "BANDAID",
    bp: "",
    sugar: "",
    weight: "",
    age: 43,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "16/11/25",
    name: "VIKAAS",
    empId: "",
    department: "GELETING",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Injury",
    medicine: "BANDAID",
    bp: "",
    sugar: "",
    weight: "",
    age: 36,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "21/11/25",
    name: "RAMAKANT",
    empId: "",
    department: "BSR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Injury",
    medicine: "BANDAID",
    bp: "",
    sugar: "",
    weight: "",
    age: 43,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "26/11/25",
    name: "RAVI JANJOTRI",
    empId: "",
    department: "ESD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Injury",
    medicine: "BANDAID",
    bp: "",
    sugar: "",
    weight: "",
    age: 30,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "29/11/25",
    name: "KIRAN KABLE",
    empId: "",
    department: "ETP",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Injury",
    medicine: "BANDAID",
    bp: "",
    sugar: "",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "11/11/25",
    name: "SHRIKANT BILLA",
    empId: "",
    department: "RND",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "",
    medicine: "T.CYCLOPAM",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "RAHUL CHAVHAN",
    empId: "",
    department: "PFD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "",
    medicine: "T.CYCLOPAM",
    bp: "",
    sugar: "",
    weight: "",
    age: 19,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "14/11/25",
    name: "DYANAD KORLEKAR",
    empId: "",
    department: "SUP S/G",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "",
    medicine: "T.CYCLOPAM",
    bp: "",
    sugar: "",
    weight: "",
    age: 44,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "18/11/25",
    name: "VINOD YADAV",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "",
    medicine: "T.CYCLOPAM",
    bp: "",
    sugar: "",
    weight: "",
    age: 34,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "26/11/25",
    name: "NIRAJ WARLI",
    empId: "",
    department: "ESD",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "",
    medicine: "T.CYCLOPAM",
    bp: "",
    sugar: "",
    weight: "",
    age: 32,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "07/11/25",
    name: "ISHWAR SOLNKI",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Blood sugar checking",
    medicine: "NA",
    bp: "",
    sugar: "112MGDL",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "16/11/25",
    name: "RAMESH  SINGH",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Blood sugar checking",
    medicine: "128-",
    bp: "",
    sugar: "",
    weight: "",
    age: 40,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "21/11/25",
    name: "MAHENDRA KABLE",
    empId: "",
    department: "MUTICAR",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Blood sugar checking",
    medicine: "203-",
    bp: "",
    sugar: "",
    weight: "",
    age: 53,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "22/11/25",
    name: "RANJIT NAYAK",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Blood sugar checking",
    medicine: "123-155",
    bp: "",
    sugar: "",
    weight: "",
    age: 48,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "22/11/25",
    name: "DAYAND KORALEKAR",
    empId: "",
    department: "SERVICES",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "",
    primaryComplaint: "Blood sugar checking",
    medicine: "118-",
    bp: "",
    sugar: "",
    weight: "",
    age: 44,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
  {
    date: "06/11/25",
    name: "ROSHAN BHAGDE",
    empId: "",
    department: "QA",
    bodyPartPrimaryLocation: "",
    bodyPartPrimary: "Tooth",
    primaryComplaint: "Pain",
    medicine: "T.BRUFEN",
    bp: "",
    sugar: "",
    weight: "",
    age: 25,
    next_appointment_date: "",
    gender: "MALE",
    remarks: "",
  },
]?.map((item) => ({
  ...item,
  age: item?.age?.toString(),
  // mobile: item?.mobile?.toString(),
  ohcType: "OPD",
  // empId: item?.empId?.toString(),
  corpId: "25a81d71-7cfb-4f3e-9927-a94ca55017a5",
  // gender: item.gender === "M" ? "MALE" : item.gender === "F" ? "FEMALE" : "",
}));

const cleanAndNormalizeData = (data) => {
  if (!Array.isArray(data)) return [];

  // ✅ List of all supported formats — short, long, and mixed
  const dateFormats = [
    "D-MMM-YY",
    "DD-MMM-YY",
    "D-MMM-YYYY",
    "DD-MMM-YYYY",
    "D/M/YYYY",
    "DD/M/YYYY",
    "D/MM/YYYY",
    "DD/MM/YYYY",
    "D-M-YYYY",
    "DD-MM-YYYY",
    "DD-MM-YY",
    "D-M-YY",
    "M/D/YYYY",
    "MM/DD/YYYY",
    "M/D/YY",
    "MM/DD/YY",
    "YYYY-MM-DD",
    "YYYY/MM/DD",
    "YYYY-M-D",
    "D MMM YYYY",
    "D MMM YY",
    "DD/MM/YY",
    "D/M/YY",
  ];

  return data.map((item) => {
    const normalized = { ...item };

    // --- 1️⃣ Normalize date to YYYY-MM-DD ---
    let parsedDate = null;
    if (normalized.date) {
      // Try all known formats
      for (const fmt of dateFormats) {
        const tryParse = dayjs(normalized.date, fmt, true);
        if (tryParse.isValid()) {
          parsedDate = tryParse;
          break;
        }
      }

      // If none worked, try free-form parse (last resort)
      if (!parsedDate) {
        const autoParsed = dayjs(normalized.date);
        if (autoParsed.isValid()) parsedDate = autoParsed;
      }

      normalized.date = parsedDate ? parsedDate.format("YYYY-MM-DD") : "";
    } else {
      normalized.date = "";
    }

    // --- 2️⃣ Generate caseRecordTimeStamp ---
    const dateStr = normalized.date?.trim?.();
    const timeStr = normalized.caseRecordTimeStamp?.trim?.();

    if (dateStr && timeStr && !timeStr.includes("T")) {
      let parsed = dayjs(`${dateStr} ${timeStr}`, [
        "YYYY-MM-DD HH:mm",
        "YYYY-MM-DD hh:mm A",
        "YYYY-MM-DD H:mm",
        "YYYY-MM-DD h:mm A",
      ]);

      normalized.caseRecordTimeStamp = parsed.isValid()
        ? parsed.utc().format("YYYY-MM-DDTHH:mm:ss.SSS[Z]")
        : "";
    } else if (timeStr && timeStr.includes("T")) {
      const parsed = dayjs(timeStr);
      normalized.caseRecordTimeStamp = parsed.isValid()
        ? parsed.utc().format("YYYY-MM-DDTHH:mm:ss.SSS[Z]")
        : "";
    } else {
      normalized.caseRecordTimeStamp = "";
    }

    // --- 3️⃣ Remove null/empty fields ---
    const cleaned = Object.fromEntries(
      Object.entries(normalized).filter(([_, value]) => {
        if (value === null || value === undefined) return false;
        if (typeof value === "string" && value.trim() === "") return false;
        if (Array.isArray(value) && value.length === 0) return false;
        return true;
      })
    );

    return cleaned;
  });
};

const UploadDataOPD = ({}) => {
  // const cleanedData = useMemo(() => cleanObject(rawData), [rawData]);
  const formatted = useMemo(() => cleanAndNormalizeData(rawData), [rawData]);

  console.log({ formatted });

  return <div></div>;
};

export default UploadDataOPD;
