export const BASE_URL_AUTH = "https://auth.uno.care/";
export const BASE_URL = "https://apibackend.uno.care/api/";
// export const BASE_URL = "https://apitest.uno.care/api/";

export const authHeader_local =
  "eyJhbGciOiJIUzUxMiJ9.eyJicmFuY2hJZCI6bnVsbCwic3ViIjoidGVzdC5yZXBvcnRpbmdAdW5vLmNhcmUiLCJyb2xlIjoiUkVQT1JUSU5HX0FETUlOIiwicm9sZXMiOlsiUkVQT1JUSU5HX0FETUlOIiwiSEVBTFRIQ0FNUCIsIkVOR0FHRU1FTlQiXSwibmFtZSI6bnVsbCwibW9iaWxlIjpudWxsLCJicmFuY2hOYW1lIjoiR2hhdGFiaWxvZCIsImlkIjoxNTczLCJwb3J0YWwiOiJSRVBPUlRJTkciLCJleHAiOjE3Mzk5NzExNzgsInVzZXJJRCI6ImVjMjZiYWRkLTEzNTMtNDMwMS1hNWRiLTg5N2ZhMzdlZThhOCIsImlhdCI6MTczMjE5NTE3OH0.GBkBVE7rekcBA7NUuVvQMOzH0QlHUgc5z2fPfxAiuLg7R9s0cZv8839zuTp72ZBRedBdX-3lXrbbb7zW6lBrmA";
