export const data3 = [
  {
    employeeId: "9",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "23",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "26",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "2",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "11",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "3",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "21",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "22",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "15",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "16",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "29",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "27",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "25",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "24",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "1001536",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "1002800",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "18",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "12",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "20",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "30",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "28",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "7",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "6",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "8",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "17",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "14",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "1",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "13",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "4",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "1005169",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "19",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "5",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "10",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
].map((item) => ({
  empId: item.employeeId,
  nearLeftEyeSight: item.nearLeftEyeSight,
  nearRightEyeSight: item.nearRightEyeSight,
  farRightEyeSight: item.farRightEyeSight,
  farLeftEyeSight: item.farLeftEyeSight,
}));
