export const data3 = [
  {
    employeeId: "TDS/BALAJI/669",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/657",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/028",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/200",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/047",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/502",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/568",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/640",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/682",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/692",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/695",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/702",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/740",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/722",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/739",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/732",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/492",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/494",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/505",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/549",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/561",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/650",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/665",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "TDS/BALAJI/693",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "ADITI/ISCON/1028",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "ADITI/ISCON/1082",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "ADITI/ISCON/1085",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "ADITI/ISCON/1106",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "ADITI/ISCON/1181",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "ADITI/ISCON/1408",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "ADITI/ISCON/1394",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
  {
    employeeId: "ADITI/ISCON/1007",
    nearLeftEyeSight: "N/6",
    nearRightEyeSight: "N/6",
    farRightEyeSight: "6/6",
    farLeftEyeSight: "6/6",
  },
].map((item) => ({
  empId: item.employeeId,
  nearLeftEyeSight: item.nearLeftEyeSight,
  nearRightEyeSight: item.nearRightEyeSight,
  farRightEyeSight: item.farRightEyeSight,
  farLeftEyeSight: item.farLeftEyeSight,
}));
